-- DROP TABLES
DROP TABLE estoque CASCADE CONSTRAINTS;
DROP TABLE produto CASCADE CONSTRAINTS;

-- CREATE TABLE produto
CREATE TABLE estoque (
                         id NUMBER PRIMARY KEY,
                         produto_id NUMBER NOT NULL,
                         quantidade NUMBER NOT NULL,
                         CONSTRAINT fk_estoque_produto
                             FOREIGN KEY (produto_id)
                                 REFERENCES produto(id)
);

CREATE TABLE produto (
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         nome VARCHAR2(100) NOT NULL,
                         descricao VARCHAR2(255),
                         categoria VARCHAR2(100)
);
