
CREATE TABLE main_course (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10,2) NOT NULL,
    available NUMBER(1) NOT NULL,
    calories NUMBER,
    vegan NUMBER(1),
    gluten_free NUMBER(1),
    main_course_type VARCHAR2(50),
    spice_level VARCHAR2(50),
    cooking_method VARCHAR2(100),
    dietary_preferences CLOB,
    organic NUMBER(1),
    source VARCHAR2(100),
    halal NUMBER(1),
    kosher NUMBER(1)
);

CREATE TABLE entree (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10,2) NOT NULL,
    available NUMBER(1) NOT NULL,
    calories NUMBER,
    vegan NUMBER(1),
    glutenFree NUMBER(1),
    entreeType VARCHAR2(50),
    portionSize VARCHAR2(50),
    mainIngredients CLOB,
    servingMethod VARCHAR2(100)
);

CREATE TABLE dessert (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    available NUMBER(1),
    calories NUMBER,
    vegan NUMBER(1),
    gluten_free NUMBER(1),
    dessert_type VARCHAR2(50),
    flavor VARCHAR2(50),
    temperature VARCHAR2(50),
    allergens VARCHAR2(100),
    sweetness_level VARCHAR2(50),
    portion_size VARCHAR2(50),
    main_ingredients CLOB,
    health_info CLOB
);






