CREATE TABLE main_course (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10,2) NOT NULL,
    available NUMBER(1) NOT NULL,
    calories NUMBER,
    vegan NUMBER(1),
    gluten_free NUMBER(1),
    main_course_type VARCHAR2(50),
    spice_level VARCHAR2(50),
    cooking_method VARCHAR2(100),
    dietary_preferences CLOB,
    organic NUMBER(1),
    source VARCHAR2(100),
    halal NUMBER(1),
    kosher NUMBER(1)
);

CREATE TABLE main_course_produto (
    main_course_id NUMBER,
    produto_id NUMBER,
    PRIMARY KEY (main_course_id, produto_id),
    FOREIGN KEY (main_course_id) REFERENCES main_course(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produto(id)
);

CREATE TABLE entree (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10,2) NOT NULL,
    available NUMBER(1) NOT NULL,
    calories NUMBER,
    vegan NUMBER(1),
    glutenFree NUMBER(1),
    entreeType VARCHAR2(50),
    portionSize VARCHAR2(50),
    mainIngredients CLOB,
    servingMethod VARCHAR2(100)
);

CREATE TABLE entree_produto (
    entree_id NUMBER,
    produto_id NUMBER,
    PRIMARY KEY (entree_id, produto_id),
    FOREIGN KEY (entree_id) REFERENCES entree(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produto(id)
);

CREATE TABLE dessert (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    available NUMBER(1),
    calories NUMBER,
    vegan NUMBER(1),
    gluten_free NUMBER(1),
    dessert_type VARCHAR2(50),
    flavor VARCHAR2(50),
    temperature VARCHAR2(50),
    allergens VARCHAR2(100),
    sweetness_level VARCHAR2(50),
    portion_size VARCHAR2(50),
    main_ingredients CLOB,
    health_info CLOB
);

CREATE TABLE dessert_produto (
    dessert_id NUMBER,
    produto_id NUMBER,
    PRIMARY KEY (dessert_id, produto_id),
    FOREIGN KEY (dessert_id) REFERENCES dessert(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produto(id)
);

CREATE TABLE drink (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    available NUMBER(1),
    calories NUMBER,
    vegan NUMBER(1),
    gluten_free NUMBER(1),
    alcoholic NUMBER(1),
    drink_type VARCHAR2(50),
    container VARCHAR2(50),
    flavor VARCHAR2(50),
    carbonated NUMBER(1),
    size VARCHAR2(20),
    drink_temperature VARCHAR2(20)
);

CREATE TABLE drink_produto (
    drink_id NUMBER,
    produto_id NUMBER,
    PRIMARY KEY (drink_id, produto_id),
    FOREIGN KEY (drink_id) REFERENCES drink(id) ON DELETE CASCADE,
    FOREIGN KEY (produto_id) REFERENCES produto(id)
);
