-- Drop existing tables and sequences
DROP TABLE COZINHEIRO          CASCADE CONSTRAINTS;
DROP TABLE GARCOM              CASCADE CONSTRAINTS;
DROP TABLE GERENTE             CASCADE CONSTRAINTS;
DROP TABLE FUNCIONARIO         CASCADE CONSTRAINTS;
DROP TABLE PESSOA              CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PESSOA_ID;
DROP SEQUENCE SEQ_FUNCIONARIO_ID;

-- Create PESSOA table
CREATE TABLE PESSOA (
    ID_PESSOA       NUMBER PRIMARY KEY,
    NOME            VARCHAR2(100) NOT NULL,
    TELEFONE        VARCHAR2(20) NOT NULL,
    EMAIL           VARCHAR2(100) NOT NULL,
    CPF             VARCHAR2(14) NOT NULL
);

-- Create FUNCIONARIO table
CREATE TABLE FUNCIONARIO (
    ID_FUNCIONARIO  NUMBER PRIMARY KEY,
    ID_PESSOA       NUMBER NOT NULL,
    CARGO           VARCHAR2(50),
    SALARIO         NUMBER NOT NULL,
    COMISSAO        NUMBER,
    TURNO           VARCHAR2(20) NOT NULL,
    DATA_ADMISSAO   DATE NOT NULL,
    CONSTRAINT FK_FUNCIONARIO_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

-- Create COZINHEIRO table
CREATE TABLE COZINHEIRO (
    ID_COZINHEIRO   NUMBER PRIMARY KEY,
    ID_FUNCIONARIO  NUMBER NOT NULL,
    ESPECIALIDADE   VARCHAR2(100) NOT NULL,
    ANOS_EXPERIENCIA NUMBER NOT NULL,
    CONSTRAINT FK_COZINHEIRO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

-- Create GARCOM table
CREATE TABLE GARCOM (
    ID_GARCOM       NUMBER PRIMARY KEY,
    ID_FUNCIONARIO  NUMBER NOT NULL,
    IDIOMAS         VARCHAR2(200) NOT NULL,
    EXPERIENCIA     NUMBER NOT NULL,
    CONSTRAINT FK_GARCOM_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

-- Create GERENTE table
CREATE TABLE GERENTE (
    ID_GERENTE      NUMBER PRIMARY KEY,
    ID_FUNCIONARIO  NUMBER NOT NULL,
    DEPARTAMENTO    VARCHAR2(100) NOT NULL,
    BONIFICACAO     NUMBER,
    CONSTRAINT FK_GERENTE_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(ID_FUNCIONARIO)
);

-- Create sequences for PESSOA and FUNCIONARIO
CREATE SEQUENCE SEQ_PESSOA_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_FUNCIONARIO_ID START WITH 1 INCREMENT BY 1;

-- Create triggers for PESSOA and FUNCIONARIO
CREATE OR REPLACE TRIGGER TRG_PESSOA_ID
BEFORE INSERT ON PESSOA
FOR EACH ROW
BEGIN
  :new.ID_PESSOA := SEQ_PESSOA_ID.NEXTVAL;
END;

CREATE OR REPLACE TRIGGER TRG_FUNCIONARIO_ID
BEFORE INSERT ON FUNCIONARIO
FOR EACH ROW
BEGIN
  :new.ID_FUNCIONARIO := SEQ_FUNCIONARIO_ID.NEXTVAL;
END;