-- Drop existing table and sequence
DROP TABLE PAGAMENTO CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_PAGAMENTO_ID;

-- Create PAGAMENTO table
CREATE TABLE PAGAMENTO (
    ID_PAGAMENTO     NUMBER PRIMARY KEY,
    VALOR            NUMBER(10,2) NOT NULL,
    DATA_HORA        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TIPO_PAGAMENTO   VARCHAR2(20) NOT NULL
);

-- Create sequence for PAGAMENTO
CREATE SEQUENCE SEQ_PAGAMENTO_ID START WITH 1 INCREMENT BY 1;

-- Create trigger for PAGAMENTO
CREATE OR REPLACE TRIGGER TRG_PAGAMENTO_ID
BEFORE INSERT ON PAGAMENTO
FOR EACH ROW
BEGIN
    :new.ID_PAGAMENTO := SEQ_PAGAMENTO_ID.NEXTVAL;
END;
/
